import { ipcMain } from 'electron'
import { createHash } from 'crypto'
import { promises as fs } from 'fs'
import { extname, join } from 'path'
import type { CanvasDoc, PersistedMessage, ThreadDoc } from '../shared/types'
import {
  CLAUDE_MD_FILE,
  CLAUDE_MD_ID,
  CLAUDE_MD_POS,
  canvasFileFor,
  clipRelFor,
  getFolderRoot,
  isSafeFileRel,
  isSafeNodeId,
  isSafeNoteFile,
  memoryFileFor,
  readTextIfExists,
  threadFileFor,
  threadsDirFor
} from './paths'
import {
  createNoteFile,
  ensureClaudeMdFile,
  moveNoteFile,
  noteFiles,
  notePathFor,
  readNoteVersions
} from './notes'
import { fileMimeFor, imageDataUrl } from './files'

// Layout/metadata only — transcripts and note bodies live in their own files.
// Note filenames come from the main process's map, not the renderer's doc.
export async function writeCanvasFile(root: string, doc: CanvasDoc): Promise<void> {
  const dir = join(root, '.canvas')
  await fs.mkdir(dir, { recursive: true })
  const slim = {
    ...doc,
    nodes: doc.nodes.map((node) => {
      const copy = { ...node }
      delete copy.messages
      delete copy.content
      delete copy.noteVersions
      delete copy.file
      delete copy.dataUrl
      const file =
        node.kind === 'note'
          ? noteFiles.get(node.id)
          : node.kind === 'file' && node.file && isSafeFileRel(node.file)
            ? node.file
            : undefined
      if (file) copy.file = file
      return copy
    })
  }
  await fs.writeFile(join(dir, 'canvas.json'), JSON.stringify(slim, null, 2))
}

// --- Project memory index (MEMORY.md) -----------------------------------
// One markdown line per pinned resource — a note, image or PDF: a titled link
// to its file plus the cached description. This is the text injected into every
// chat's system prompt and shown in the Memory legend — the app owns it end to
// end. The agent opens whichever files it needs with the Read tool, which reads
// images and PDFs as natively as markdown, so no resource kind needs special
// injection — it's all just file links.

export function buildMemoryIndex(doc: CanvasDoc): string {
  const lines = doc.nodes.flatMap((node) => {
    if (!node.pinned) return []
    // Notes are addressed through the id→filename map (their file is retitled
    // independently); files carry their own relative path; links and chats point
    // at the hidden clip captured when they were pinned (a chat's clip is its
    // transcript dumped to markdown). A chat carries no `kind` (omitted == chat).
    const file =
      node.kind === 'note'
        ? noteFiles.get(node.id)
        : node.kind === 'file'
          ? node.file
          : node.kind === 'link' || node.kind === undefined
            ? clipRelFor(node.id)
            : undefined
    if (!file) return []
    const title =
      node.title?.trim() ||
      (node.kind === 'link' ? node.url : undefined) ||
      (node.kind === undefined ? 'Chat' : file.replace(/\.[^.]+$/, ''))
    const desc = node.description?.trim()
    return [`- [${title}](${file})${desc ? ` — ${desc}` : ''}`]
  })
  if (lines.length === 0) return ''
  return (
    '# Project memory\n\n' +
    '<!-- Auto-generated by thinking-canvas from pinned notes. Do not edit by hand. -->\n\n' +
    lines.join('\n') +
    '\n'
  )
}

// Rewrite MEMORY.md only when the index actually changed; remove it once the
// last note is unpinned. Compared against the file itself, so it stays correct
// across folder switches without any cached state.
export async function syncMemoryIndex(root: string, doc: CanvasDoc): Promise<void> {
  const index = buildMemoryIndex(doc)
  const path = memoryFileFor(root)
  const current = await readTextIfExists(path)
  if (index === current) return
  if (index === '') {
    try {
      await fs.unlink(path)
    } catch {
      // nothing to remove
    }
    return
  }
  await fs.writeFile(path, index)
}

// Surface the folder's top-level files as cards so opening a folder reveals
// what's in it. Supported kinds only — markdown notes, PDFs and images;
// already-referenced files, hidden files and subdirectories are skipped. Ids are
// derived from the filename (sha1) so a reload never double-places the same file,
// and the moment the user moves a card the next save pins it — from then on it
// loads as an ordinary node and this pass leaves it alone. Positions are
// provisional, laid out in a grid to the right of the CLAUDE.md card.
export async function autoPlaceTopLevel(root: string, doc: CanvasDoc): Promise<void> {
  const entries = await fs.readdir(root, { withFileTypes: true }).catch(() => [])
  const takenNotes = new Set(noteFiles.values()) // title-named .md + CLAUDE.md
  const takenMedia = new Set(
    doc.nodes.filter((n) => n.kind === 'file' && n.file).map((n) => n.file)
  )
  const skipMd = new Set([CLAUDE_MD_FILE, 'MEMORY.md'])
  const autoId = (kind: string, name: string): string =>
    `auto-${kind}-${createHash('sha1').update(name).digest('hex').slice(0, 12)}`
  let placed = 0
  const nextPos = (): { x: number; y: number } => {
    const col = placed % 3
    const row = Math.floor(placed / 3)
    placed++
    return { x: 1040 + col * 340, y: 32 + row * 260 }
  }
  for (const ent of [...entries].sort((a, b) => a.name.localeCompare(b.name))) {
    if (!ent.isFile() || ent.name.startsWith('.')) continue
    const name = ent.name
    if (extname(name).toLowerCase() === '.md') {
      if (skipMd.has(name) || takenNotes.has(name) || !isSafeNoteFile(name)) continue
      const id = autoId('note', name)
      if (doc.nodes.some((n) => n.id === id)) continue
      noteFiles.set(id, name)
      doc.nodes.push({
        id,
        kind: 'note',
        position: nextPos(),
        width: 380,
        title: name.replace(/\.md$/i, ''),
        file: name,
        content: await readTextIfExists(join(root, name)),
        noteVersions: await readNoteVersions(root, id)
      })
      continue
    }
    const mime = fileMimeFor(name)
    if (!mime || takenMedia.has(name) || !isSafeFileRel(name)) continue
    const id = autoId('file', name)
    if (doc.nodes.some((n) => n.id === id)) continue
    doc.nodes.push({
      id,
      kind: 'file',
      position: nextPos(),
      width: 300,
      title: name,
      file: name,
      dataUrl: mime === 'application/pdf' ? undefined : await imageDataUrl(root, name)
    })
  }
}

export function registerCanvasIpc(): void {
  ipcMain.handle('canvas:load', async (): Promise<CanvasDoc | null> => {
    const root = getFolderRoot()
    if (!root) return null
    noteFiles.clear()
    // The CLAUDE.md node is always present and always backed by the root file,
    // whatever canvas.json says — map it before the migration loop, and inject
    // the node for canvases that predate the feature (its body hydrates below).
    noteFiles.set(CLAUDE_MD_ID, CLAUDE_MD_FILE)
    await ensureClaudeMdFile(root)
    try {
      let doc: CanvasDoc
      try {
        doc = JSON.parse(await fs.readFile(canvasFileFor(root), 'utf8'))
      } catch {
        // No canvas.json yet (a fresh folder) — start empty; the CLAUDE.md
        // inject below and the auto-placement pass fill it in. Not persisted
        // here, so opening a folder never writes to it on its own.
        doc = { version: 1, nodes: [], edges: [], viewport: { x: 0, y: 0, zoom: 1 } }
      }
      if (!doc.nodes.some((n) => n.id === CLAUDE_MD_ID)) {
        doc.nodes.unshift({
          id: CLAUDE_MD_ID,
          kind: 'note',
          system: 'claudeMd',
          position: CLAUDE_MD_POS,
          width: 600,
          title: CLAUDE_MD_FILE,
          file: CLAUDE_MD_FILE
        })
      }
      // One-time migration: notes that predate title-named files move from
      // .canvas/notes/<id>.md to "<title>.md" at the folder root.
      let migrated = false
      for (const node of doc.nodes) {
        if (node.kind !== 'note' || !isSafeNodeId(node.id)) continue
        if (node.id === CLAUDE_MD_ID) continue // fixed file, mapped above
        if (node.file && isSafeNoteFile(node.file)) {
          noteFiles.set(node.id, node.file)
          continue
        }
        const legacyRel = join('.canvas', 'notes', `${node.id}.md`)
        let slot: { title: string; file: string }
        try {
          await fs.access(join(root, legacyRel))
          slot = await moveNoteFile(root, legacyRel, node.title)
        } catch {
          slot = await createNoteFile(root, node.title)
        }
        noteFiles.set(node.id, slot.file)
        node.file = slot.file
        // collision or sanitization may have adjusted a non-empty title
        if (node.title) node.title = slot.title
        migrated = true
      }
      if (migrated) await writeCanvasFile(root, doc)
      // Nodes that predate updatedAt borrow their backing file's mtime so
      // the sidebar's recency order is right from the first load; the next
      // canvas save makes the stamp durable.
      const mtimeOf = async (path: string): Promise<number | undefined> => {
        try {
          return Math.round((await fs.stat(path)).mtimeMs)
        } catch {
          return undefined
        }
      }
      // Transcripts and note contents live one file per node — rejoin them.
      await Promise.all(
        doc.nodes.map(async (node) => {
          if (!isSafeNodeId(node.id)) return
          if (node.kind === 'link') return // the URL rides canvas.json itself
          if (node.kind === 'file') {
            if (node.file && isSafeFileRel(node.file)) {
              node.dataUrl = await imageDataUrl(root, node.file)
            }
            return
          }
          if (node.kind === 'note') {
            const path = notePathFor(root, node.id)
            node.content = path ? await readTextIfExists(path) : ''
            node.noteVersions = await readNoteVersions(root, node.id)
            if (node.updatedAt == null && path) node.updatedAt = await mtimeOf(path)
            return
          }
          try {
            const thread: ThreadDoc = JSON.parse(
              await fs.readFile(threadFileFor(root, node.id), 'utf8')
            )
            node.messages = thread.messages
            if (node.updatedAt == null) {
              node.updatedAt = await mtimeOf(threadFileFor(root, node.id))
            }
          } catch {
            // no transcript yet
          }
        })
      )
      await autoPlaceTopLevel(root, doc)
      return doc
    } catch {
      return null
    }
  })

  ipcMain.handle('canvas:save', async (_event, doc: CanvasDoc): Promise<void> => {
    const root = getFolderRoot()
    if (!root) return
    await writeCanvasFile(root, doc)
    await syncMemoryIndex(root, doc)
  })

  ipcMain.handle(
    'canvas:saveThread',
    async (_event, nodeId: string, messages: PersistedMessage[]): Promise<void> => {
      const root = getFolderRoot()
      if (!root || !isSafeNodeId(nodeId)) return
      await fs.mkdir(threadsDirFor(root), { recursive: true })
      const thread: ThreadDoc = { version: 1, messages }
      await fs.writeFile(threadFileFor(root, nodeId), JSON.stringify(thread, null, 2))
    }
  )

  ipcMain.handle('canvas:deleteThread', async (_event, nodeId: string): Promise<void> => {
    const root = getFolderRoot()
    if (!root || !isSafeNodeId(nodeId)) return
    try {
      await fs.unlink(threadFileFor(root, nodeId))
    } catch {
      // never had a transcript
    }
  })
}
