import { promises as fs } from 'fs'
import { join } from 'path'

// The folder the canvas is rooted at: the agent's cwd and the home of
// .canvas/canvas.json. Chosen by the user and remembered across launches —
// null until a folder has been picked (the renderer shows a picker prompt).
let folderRoot: string | null = null

export const getFolderRoot = (): string | null => folderRoot

export const setFolderRoot = (root: string | null): void => {
  folderRoot = root
}

export const canvasFileFor = (root: string): string => join(root, '.canvas', 'canvas.json')
// The project memory index — a real, user-visible file at the folder root,
// regenerated by the app from pinned notes (never hand-edited).
export const memoryFileFor = (root: string): string => join(root, 'MEMORY.md')

// The always-present CLAUDE.md node: a note whose live body IS the folder's
// CLAUDE.md (the agent's project instructions, appended to every chat turn's
// system prompt — read manually, not via settingSources; see the send handler).
// Fixed id and filename — the renderer injects the node, main hard-maps it to
// the root file regardless of what canvas.json recorded.
export const CLAUDE_MD_ID = 'claude-md'
export const CLAUDE_MD_FILE = 'CLAUDE.md'
export const CLAUDE_MD_POS = { x: 360, y: 32 } // clear of the top-left canvas legends
export const threadsDirFor = (root: string): string => join(root, '.canvas', 'threads')
export const threadFileFor = (root: string, nodeId: string): string =>
  join(threadsDirFor(root), `${nodeId}.json`)
// Pre-migration note bodies live here, keyed by node id. Version sidecars
// still live here too (the live body moved to a title-named root file, but its
// history stays keyed by the stable node id, out of the user's file view).
export const noteMetaDirFor = (root: string): string => join(root, '.canvas', 'notes')
export const legacyNoteFileFor = (root: string, nodeId: string): string =>
  join(noteMetaDirFor(root), `${nodeId}.md`)
export const noteVersionsFileFor = (root: string, nodeId: string): string =>
  join(noteMetaDirFor(root), `${nodeId}.versions.json`)
// A pinned link's clipped page: the Defuddle markdown captured from the live tab
// at pin time, kept as hidden metadata (keyed by node id, not a root note) so it
// doesn't clutter the user's own files. The agent Reads it on demand through its
// MEMORY.md line; re-clipping overwrites it.
export const clipsDirFor = (root: string): string => join(root, '.canvas', 'clips')
export const clipFileFor = (root: string, nodeId: string): string =>
  join(clipsDirFor(root), `${nodeId}.md`)
// Its MEMORY.md link target — relative to root, posix-style for the markdown.
export const clipRelFor = (nodeId: string): string => `.canvas/clips/${nodeId}.md`

// AI-authored widget cards: one HTML document per node, keyed by node id
// (hidden metadata like thread transcripts — never in the user's file view).
export const widgetsDirFor = (root: string): string => join(root, '.canvas', 'widgets')
export const widgetFileFor = (root: string, nodeId: string): string =>
  join(widgetsDirFor(root), `${nodeId}.html`)

// Node ids come from the renderer over IPC — keep them path-segment safe.
export const isSafeNodeId = (nodeId: string): boolean => /^[\w-]+$/.test(nodeId)

// Filenames round-trip through canvas.json — only accept plain root-level
// markdown filenames on the way back in.
export const isSafeNoteFile = (file: string): boolean =>
  /^[^/\\]+\.md$/.test(file) && !file.startsWith('.')

// Filename = title: keep it human, strip only what a path can't take.
export function sanitizeTitle(title: string): string {
  return title
    .replace(/[/\\:]/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/^[.\s]+/, '') // no hidden files
    .replace(/[.\s]+$/, '')
    .slice(0, 120)
    .trim()
}

export async function readTextIfExists(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf8')
  } catch {
    return ''
  }
}

// File-node paths round-trip through canvas.json — accept only relative
// paths that stay inside the root, with no hidden or parent segments.
export const isSafeFileRel = (rel: string): boolean =>
  rel.length > 0 &&
  !rel.includes('\\') &&
  rel.split('/').every((seg) => seg !== '' && !seg.startsWith('.'))

export async function dirExists(path: string): Promise<boolean> {
  try {
    return (await fs.stat(path)).isDirectory()
  } catch {
    return false
  }
}
